### ISSUE TITLE
[Bug]: Inverter won't start charging during time-of-use period. Restarting HA corrects the issue. But why?

### ISSUE THREAD

**Issue by ctepelea** [Pho3niX90/solis_modbus#167]
I have a very strange behaviour. My S5-EH1 is configured in a time-use scenario to load during the day (charge-slot 1 from 10:45 to 17:00) and to discharge during the night.

I am tracking the available solar power to regulate the charging current via the Write Register Service and to same during the night to modulate the discharge based on load (negative power).

It is a single-phase inverter on a complicated setup with another three-phase inverter and I do not have a three-phase power meter connected to the Solis S5. Just so people do not ask me why I do not use the self-use operating mode.

Now, here is my bug. And it is quite strange. The inverter will not start charging the batteries even after 10:45 (start of the charge slot 1 charging). I've tried flipping all switches, changing the time of use times, etc. If I put it in reserve battery mode it starts charging at 100A, when I flip back it manifests the same behaviour. It won't charge even if time-charging is turned on and it is within that interval.

There is ONE thing that will make the inverter behave normally. IF I RESTART HOMEASSISTANT. Almost 100% of the cases but not absolutely always. This has been going on for 60-90 days so it is pretty well documented, it's not just some quirk.

At the end of the charge period, the flipping to discharge mode works without glitch.

What to do? I don't even know what logs I could provide...

Thanks for any ideas.

**Comment by ctepelea** [comment]
Sorry, I think I've figured it out. The inverter clock is off. Just trying to remotely figure out how to set the clock.

**Comment by ctepelea** [comment]
sequence:
    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43000
        value: "{{ now().year % 100 }}"  # Extracts last two digits of the year

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43001
        value: "{{ now().month }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43002
        value: "{{ now().day }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43003
        value: "{{ now().hour }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43004
        value: "{{ now().minute }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43005
        value: "{{ now().second }}"
        
alias: "Solis: Set Inverter Date and Time"
description: ""

**Comment by ctepelea** [comment]
I have used the following HA script to set the time on the inverter.

```
sequence:
    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43000
        value: "{{ now().year % 100 }}"  # Extracts last two digits of the year

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43001
        value: "{{ now().month }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43002
        value: "{{ now().day }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43003
        value: "{{ now().hour }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43004
        value: "{{ now().minute }}"

    - action: solis_modbus.solis_write_holding_register
      data:
        address: 43005
        value: "{{ now().second }}"
        
alias: "Solis: Set Inverter Date and Time"
description: ""
```
