### ISSUE TITLE
[Bug]: Trying to get my head arround the working mode

### ISSUE THREAD

**Issue by Pluimvee** [Pho3niX90/solis_modbus#218]
Each time I try to put the inverter to standby it starts to charge. So I dug into all the workmodes and settings trying to find out what was telling it to start charging. And I got a bit lost, or even confused

In _select.py_ (line 40) there is a workmode specified
```yaml
         "register": 43110,
            "name": "Work Mode",
            "entities": [
                {"bit_position": 0, "name": "Self-Use Mode", "work_mode": (0,1,2,6,11)},
                {"bit_position": 1, "name": "Time Of Use Mode", "work_mode": (0,1,2)},
                {"bit_position": 2, "name": "OFF-Grid Mode", "work_mode": (0,1,2)},
                {"bit_position": 6, "name": "Feed In Priority Mode", "work_mode": (0,6,11)},
                {"bit_position": 11, "name": "Solis Peak-shaving Mode", "work_mode": (0,4,6,11)},
            ]
```

Looking at the code in _solis_select_entity_ (line 74) I see that the work_mode first disables the bits of the other modes, before enabling the bit_position of the enabled mode. Some modes can not be enabled together.

``` yaml
        if bit_position is not None:
            if work_mode is not None:
                for wbit in work_mode:
                    current_register_value = set_bit(current_register_value, wbit, False)

            new_register_value: int = set_bit(current_register_value, bit_position, True)
``` 

Now instead of using the select, you can also switch the modes individually.  In the switch.py (line 29) however, there is another 'bit clearing' definition. For example the "Time Of Use Mode" and "OFF-Grid Mode" don't clean the other modes.

``` yaml
                "register": 43110,
                "entities": [
                    {"bit_position": 0, "name": "Solis Self-Use Mode", "work_mode": (0,6,11)},
                    {"bit_position": 1, "name": "Solis Time Of Use Mode"},
                    {"bit_position": 2, "name": "Solis OFF-Grid Mode"},
                    {"bit_position": 3, "name": "Solis Battery Wakeup Switch"},
                    {"bit_position": 4, "name": "Solis Reserve Battery Mode", "work_mode": (4,11)},
                    {"bit_position": 5, "name": "Solis Allow Grid To Charge The Battery"},
                    {"bit_position": 6, "name": "Solis Feed In Priority Mode", "work_mode": (0,6,11)},
                    {"bit_position": 7, "name": "Solis Batt OVC"},
                    {"bit_position": 8, "name": "Solis Battery Forcecharge Peakshaving"},
                    {"bit_position": 9, "name": "Solis Battery current correction"},
                    {"bit_position": 10, "name": "Solis Battery healing mode"},
                    {"bit_position": 11, "name": "Solis Peak-shaving Mode", "work_mode": (0,4,6,11)},
                ]
```

Looking at the functional code which uses the above definition, in _solis_binary_sensor_ (line 96), I see the same initial clearing of the work_mode bits (when the mode is enabled) after which the new mode bit is set
 
``` yaml
            if value is True and self._work_mode is not None:
                for wbit in self._work_mode:
                    current_register_value = set_bit(current_register_value, wbit, False)

            new_register_value: int = set_bit(current_register_value, self._bit_position, value)
```

Which of the above is the correct mode_clearing?

What is the diff between
- Storage control Switch value (register 43110) where the above bits are written to, and
- Storage Control Switching Value (register 33132) which is changing a bit later, but seems to leave bit 0 always enabled (Self-Use)
